/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/base/button.vue')['default']
    BaseCard: typeof import('./components/base/card.vue')['default']
    BaseDialog: typeof import('./components/base/dialog.vue')['default']
    BaseInputText: typeof import('./components/base/input-text.vue')['default']
    LayoutHeader: typeof import('./components/layout/header.vue')['default']
    LayoutSidebar: typeof import('./components/layout/sidebar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
