export default defineEventHandler((event) => {
  return {
    total: 15,
    employees: [
      {
        id: 1000,
        name: "Ana Maria Carla",
        lastRole: "Desenvolvedor iOS",
        hireDate: "01/02/1990",
        dismissalDate: "01/02/1992",
        workType: "CLT",
      },
      {
        id: 1001,
        name: "João da Silva",
        lastRole: "Analista de Sistemas",
        hireDate: "15/07/2005",
        dismissalDate: "01/01/2023",
        workType: "PJ",
      },
      {
        id: 1002,
        name: "Maria Oliveira",
        lastRole: "Engenheira de Dados",
        hireDate: "10/09/2012",
        dismissalDate: "01/02/2024",
        workType: "CLT",
      },
      {
        id: 1003,
        name: "Pedro Almeida",
        lastRole: "Analista de Negócios",
        hireDate: "20/03/2018",
        dismissalDate: "20/03/2019",
        workType: "Estagiário",
      },
      {
        id: 1004,
        name: "Juliana Santos",
        lastRole: "Designer UX/UI",
        hireDate: "05/12/2014",
        dismissalDate: "15/06/2022",
        workType: "CLT",
      },
      {
        id: 1005,
        name: "Rafael Sousa",
        lastRole: "Engenheiro de Software",
        hireDate: "03/10/2017",
        dismissalDate: "03/10/2021",
        workType: "CLT",
      },
      {
        id: 1006,
        name: "Amanda Costa",
        lastRole: "Gerente de Projetos",
        hireDate: "08/06/2010",
        dismissalDate: "01/01/2023",
        workType: "PJ",
      },
      {
        id: 1007,
        name: "Lucas Oliveira",
        lastRole: "Desenvolvedor Front-end",
        hireDate: "15/04/2019",
        dismissalDate: "15/04/2021",
        workType: "CLT",
      },
      {
        id: 1008,
        name: "Camila Santos",
        lastRole: "Analista de Dados",
        hireDate: "20/01/2015",
        dismissalDate: "20/01/2018",
        workType: "CLT",
      },
      {
        id: 1009,
        name: "Fernando Costa",
        lastRole: "Scrum Master",
        hireDate: "12/11/2016",
        dismissalDate: "12/11/2017",
        workType: "CLT",
      },
      {
        id: 1010,
        name: "Patrícia Lima",
        lastRole: "Product Manager",
        hireDate: "05/08/2013",
        dismissalDate: "01/07/2023",
        workType: "CLT",
      },
      {
        id: 1011,
        name: "Roberto Pereira",
        lastRole: "Desenvolvedor Full-stack",
        hireDate: "25/06/2011",
        dismissalDate: "25/06/2015",
        workType: "CLT",
      },
      {
        id: 1012,
        name: "Carolina Oliveira",
        lastRole: "Analista de Marketing",
        hireDate: "10/04/2017",
        dismissalDate: "10/04/2022",
        workType: "CLT",
      },
      {
        id: 1013,
        name: "André Santos",
        lastRole: "QA Engineer",
        hireDate: "30/09/2019",
        dismissalDate: "30/09/2020",
        workType: "CLT",
      },
      {
        id: 1014,
        name: "Mariana Silva",
        lastRole: "DevOps Engineer",
        hireDate: "18/02/2014",
        dismissalDate: "18/02/2023",
        workType: "CLT",
      },
      {
        id: 1015,
        name: "Ricardo Pereira",
        lastRole: "Analista de Sistemas",
        hireDate: "09/11/2018",
        dismissalDate: "09/11/2019",
        workType: "CLT",
      },
    ],
  };
});
