export default defineEventHandler((event) => {
  return {
    total: 10,
    clocks: [
      {
        date: "02/06",
        currentBalance: "+ 08h 09m",
        firstCheckIn: "09:50:30",
        lastCheckOut: "17:50:30",
        dayStatus: "Ajuste pendente",
        negative: false,
        requests: {
          id: 1,
          date: "02/06/2023",
          negative: false,
          currentBalance: "+ 08h 09m",
          hours: [
            { in: "08:30:00", out: "12:00:00" },
            { in: "13:00:00", out: "16:00:00" },
          ],
        },
      },
      {
        date: "04/06",
        currentBalance: "+ 07h 30m",
        firstCheckIn: "10:00:00",
        lastCheckOut: "17:30:00",
        dayStatus: "Em andamento",
        negative: true,
      },
      {
        date: "06/06",
        currentBalance: "+ 06h 45m",
        firstCheckIn: "09:15:00",
        lastCheckOut: "16:00:00",
        dayStatus: "Falta check-out",
        negative: true,
      },
      {
        date: "08/06",
        currentBalance: "+ 09h 00m",
        firstCheckIn: "09:00:00",
        lastCheckOut: "18:00:00",
        dayStatus: "Ponto fechado",
        negative: false,
      },
      {
        date: "10/06",
        currentBalance: "+ 08h 45m",
        firstCheckIn: "09:30:00",
        lastCheckOut: "18:15:00",
        dayStatus: "Em andamento",
        negative: false,
      },
      {
        date: "12/06",
        currentBalance: "+ 07h 15m",
        firstCheckIn: "10:15:00",
        lastCheckOut: "17:30:00",
        dayStatus: "Falta check-out",
        negative: true,
      },
      {
        date: "14/06",
        currentBalance: "+ 08h 30m",
        firstCheckIn: "09:45:00",
        lastCheckOut: "18:15:00",
        dayStatus: "Ponto fechado",
        negative: true,
      },
      {
        date: "16/06",
        currentBalance: "+ 09h 15m",
        firstCheckIn: "09:00:00",
        lastCheckOut: "18:15:00",
        dayStatus: "Ajuste pendente",
        negative: false,
      },
      {
        date: "18/06",
        currentBalance: "+ 08h 00m",
        firstCheckIn: "10:30:00",
        lastCheckOut: "18:30:00",
        dayStatus: "Em andamento",
        negative: true,
      },
      {
        date: "20/06",
        currentBalance: "+ 07h 45m",
        firstCheckIn: "09:15:00",
        lastCheckOut: "17:00:00",
        dayStatus: "Falta check-out",
        negative: false,
      },
    ],
  };
});
