export default defineEventHandler((event) => {
  return {
    total: 14,
    results: [
      {
        id: 1000,
        hour: "12:23:30",
        name: "Ana Maria Carla",
        tag: "check-out",
        department: "Design",
      },
      {
        id: 1001,
        hour: "12:22:30",
        name: "Jorge Felipe Araújo",
        tag: "check-in",
        department: "Marketing",
      },
      {
        id: 1000,
        hour: "12:23:30",
        name: "Ana Maria Carla",
        tag: "check-out",
        department: "Design",
      },
      {
        id: 1001,
        hour: "12:22:30",
        name: "Jorge Felipe Araújo",
        tag: "check-in",
        department: "Marketing",
      },
      {
        id: 1000,
        hour: "12:23:30",
        name: "Ana Maria Carla",
        tag: "check-out",
        department: "Design",
      },
      {
        id: 1001,
        hour: "12:22:30",
        name: "Jorge Felipe Araújo",
        tag: "check-in",
        department: "Marketing",
      },
      {
        id: 1000,
        hour: "12:23:30",
        name: "Ana Maria Carla",
        tag: "check-out",
        department: "Design",
      },
      {
        id: 1001,
        hour: "12:22:30",
        name: "Jorge Felipe Araújo",
        tag: "check-in",
        department: "Marketing",
      },
      {
        id: 1000,
        hour: "12:23:30",
        name: "Ana Maria Carla",
        tag: "check-out",
        department: "Design",
      },
      {
        id: 1001,
        hour: "12:22:30",
        name: "Jorge Felipe Araújo",
        tag: "check-in",
        department: "Marketing",
      },
      {
        id: 1000,
        hour: "12:23:30",
        name: "Ana Maria Carla",
        tag: "check-out",
        department: "Design",
      },
      {
        id: 1001,
        hour: "12:22:30",
        name: "Jorge Felipe Araújo",
        tag: "check-in",
        department: "Marketing",
      },
      {
        id: 1000,
        hour: "12:23:30",
        name: "Ana Maria Carla",
        tag: "check-out",
        department: "Design",
      },
      {
        id: 1001,
        hour: "12:22:30",
        name: "Jorge Felipe Araújo",
        tag: "check-in",
        department: "Marketing",
      },
    ],
  };
});
